baseURL = "https://dimex-mfg.com"
title = "Dimex"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = ["tella", "hugo-snap-gallery", "darths-hugo-shortcodes-master"]
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-11F4RFR8HF"

# Disqus Comment System
#disqusShortname = ""

[params]
  favicon ="favicon.ico"
  showBlog = true
  mainSections = ['products']
  googleFonts = true

  [params.logo]
    alt = "Dimex Logo"
    main = "img/logo/logo.png"
    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Dimex"

  [params.icon]
    fontawesome = false

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  [[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "/gallery/"
    weight = 4

  [[menu.main]]
    identifier = "location"
    name = "Location"
    url = "/location/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1


  [[menu.footer]]
    name = "Contact Us"
    url = "/contact"
    weight = 2
